keys:
  - &primary age1m47g9gt850xxdepqtuxxuh6tpat4dukmcd3emljk4ul32wfemq6sue6z8q
creation_rules:
  - path_regex: secrets/caddy$
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/radarr-api-key$
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/radarr-api-key-ev$
    key_groups:
    - age:
      - *primary
