keys:
  - &primary age1m47g9gt850xxdepqtuxxuh6tpat4dukmcd3emljk4ul32wfemq6sue6z8q
creation_rules:
  - path_regex: hosts/ct/caddy-tailscale/secrets/caddy-ev
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ct/radarr/secrets/radarr-api-key-ev
    key_groups:
    - age:
      - *primary
