keys:
  - &primary age1m47g9gt850xxdepqtuxxuh6tpat4dukmcd3emljk4ul32wfemq6sue6z8q
creation_rules:
  - path_regex: secrets/authentik-ev
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/caddy-ev
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/jellyfin-admin-pass
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/jellarr-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/lidarr-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/linkwarden-ev
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/prowlarr-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/radarr-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/sabnzbd-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/sabnzbd-eweka-creds
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/searx-ev
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/sonarr-api-key
    key_groups:
    - age:
      - *primary
