keys:
  - &primary age1m47g9gt850xxdepqtuxxuh6tpat4dukmcd3emljk4ul32wfemq6sue6z8q
creation_rules:
  - path_regex: hosts/ct/caddy-tailscale/secrets/caddy-ev
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ct/searx/secrets/searx-ev
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/vm/gpubox/secrets/jellyfin_smbaccess
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/common/lidarr-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/common/mediarr_smbaccess
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/common/radarr-api-key
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/common/sonarr-api-key
    key_groups:
    - age:
      - *primary
